# Generated by Django 2.2.13 on 2020-06-28 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20200628_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total',
            field=models.FloatField(default='1', max_length=200),
            preserve_default=False,
        ),
    ]
