# Generated by Django 3.0.7 on 2020-07-01 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_order_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='front',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_title', models.CharField(max_length=20)),
                ('card_text', models.CharField(max_length=100)),
                ('card_image', models.CharField(max_length=200)),
            ],
        ),
    ]
