# Generated by Django 2.2.13 on 2020-07-02 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_front'),
    ]

    operations = [
        migrations.AlterField(
            model_name='front',
            name='card_image',
            field=models.ImageField(upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(upload_to='pics'),
        ),
    ]
