# Generated by Django 2.2.13 on 2020-07-02 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20200702_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(height_field=1500, upload_to='men', width_field=1064),
        ),
    ]
