# Generated by Django 2.2.13 on 2020-07-03 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_auto_20200703_2228'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Fronts',
        ),
    ]
