# Generated by Django 2.2.13 on 2020-07-04 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_carousel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Carousel',
        ),
    ]
