# Generated by Django 2.2.13 on 2020-07-04 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_delete_carousel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products_Women',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('discount_price', models.FloatField()),
                ('category', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='women')),
            ],
        ),
        migrations.RenameModel(
            old_name='Products',
            new_name='Products_Men',
        ),
    ]
