# Generated by Django 2.2.13 on 2020-07-05 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_auto_20200705_0219'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Products_Women',
        ),
    ]
