# Generated by Django 2.2.13 on 2020-07-07 08:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_products_women'),
    ]

    operations = [
        migrations.AddField(
            model_name='products_men',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='products_men',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='products_men',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products_women',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='products_women',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='products_women',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
