# Generated by Django 2.2.13 on 2020-07-09 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0024_auto_20200709_2238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='title',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='title',
        ),
    ]
