# Generated by Django 2.2.13 on 2020-07-09 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0026_auto_20200709_2244'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='About1',
        ),
        migrations.RenameModel(
            old_name='About',
            new_name='Contact1',
        ),
        migrations.RenameField(
            model_name='about1',
            old_name='contactus',
            new_name='aboutus',
        ),
        migrations.RenameField(
            model_name='contact1',
            old_name='aboutus',
            new_name='contactus',
        ),
    ]
