# Generated by Django 2.2.13 on 2020-07-09 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0027_auto_20200709_2246'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About1',
        ),
        migrations.DeleteModel(
            name='Contact1',
        ),
    ]
