# Generated by Django 2.2.13 on 2020-07-10 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0031_auto_20200710_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
