# Generated by Django 2.2.13 on 2020-07-10 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0032_auto_20200710_1128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactmessage',
            name='title',
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='ip',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
