# Generated by Django 2.2.13 on 2020-07-10 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0033_auto_20200710_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='ip',
            field=models.TextField(blank=True),
        ),
    ]
