# Generated by Django 2.2.13 on 2020-07-10 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0035_auto_20200710_1132'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactForm',
        ),
        migrations.DeleteModel(
            name='ContactMessage',
        ),
    ]
