# Generated by Django 2.2.13 on 2020-07-10 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0040_auto_20200710_1147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products_men',
            name='category',
        ),
        migrations.RemoveField(
            model_name='products_women',
            name='category',
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='ip',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
