# Generated by Django 2.2.13 on 2020-07-10 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0041_auto_20200710_1148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products_men',
            name='description',
        ),
        migrations.RemoveField(
            model_name='products_men',
            name='discount_price',
        ),
        migrations.RemoveField(
            model_name='products_men',
            name='featured',
        ),
        migrations.RemoveField(
            model_name='products_men',
            name='image',
        ),
        migrations.RemoveField(
            model_name='products_men',
            name='price',
        ),
        migrations.RemoveField(
            model_name='products_men',
            name='title',
        ),
        migrations.RemoveField(
            model_name='products_women',
            name='description',
        ),
        migrations.RemoveField(
            model_name='products_women',
            name='discount_price',
        ),
        migrations.RemoveField(
            model_name='products_women',
            name='featured',
        ),
        migrations.RemoveField(
            model_name='products_women',
            name='image',
        ),
        migrations.RemoveField(
            model_name='products_women',
            name='price',
        ),
        migrations.RemoveField(
            model_name='products_women',
            name='title',
        ),
    ]
