# Generated by Django 2.2.13 on 2020-07-10 06:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0042_auto_20200710_1149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products_women',
            name='active',
        ),
        migrations.AddField(
            model_name='products_men',
            name='category',
            field=models.CharField( max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products_men',
            name='description',
            field=models.TextField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products_men',
            name='discount_price',
            field=models.FloatField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products_men',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='products_men',
            name='image',
            field=models.ImageField( upload_to='men'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products_men',
            name='price',
            field=models.FloatField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products_men',
            name='title',
            field=models.CharField( max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products_women',
            name='title',
            field=models.CharField( max_length=50),
            preserve_default=False,
        ),
    ]
