# Generated by Django 2.2.13 on 2020-07-10 06:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0043_auto_20200710_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='products_women',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='products_women',
            name='category',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='products_women',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='products_women',
            name='discount_price',
            field=models.FloatField(blank=True, default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products_women',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='products_women',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='women'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products_women',
            name='price',
            field=models.FloatField(blank=True, default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='ip',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='order',
            name='city',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='items',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='order',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='state',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.FloatField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='order',
            name='zipcode',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='products_men',
            name='category',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='products_men',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='products_men',
            name='discount_price',
            field=models.FloatField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='products_men',
            name='price',
            field=models.FloatField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='products_men',
            name='title',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='products_women',
            name='title',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
