# Generated by Django 2.2.13 on 2020-07-10 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0045_auto_20200710_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='aboutus',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='contact',
            name='contactus',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
