# Generated by Django 2.2.13 on 2020-07-10 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0047_auto_20200710_1236'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactForm',
        ),
        migrations.DeleteModel(
            name='ContactMessage',
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='order',
            name='city',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='items',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='order',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='state',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.FloatField(max_length=200),
        ),
        migrations.AlterField(
            model_name='order',
            name='zipcode',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='products_men',
            name='category',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='products_men',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='products_men',
            name='discount_price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='products_men',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='products_men',
            name='title',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='products_women',
            name='category',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='products_women',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='products_women',
            name='discount_price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='products_women',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='products_women',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
