# Generated by Django 2.2.13 on 2020-07-10 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0049_auto_20200710_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='products_men',
            name='discount_price',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='products_men',
            name='price',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='products_women',
            name='discount_price',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='products_women',
            name='price',
            field=models.CharField(max_length=50),
        ),
    ]
