# Generated by Django 2.2.13 on 2020-07-10 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0050_auto_20200710_1254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products_men',
            name='active',
        ),
        migrations.RemoveField(
            model_name='products_men',
            name='category',
        ),
        migrations.RemoveField(
            model_name='products_men',
            name='description',
        ),
        migrations.RemoveField(
            model_name='products_men',
            name='discount_price',
        ),
        migrations.RemoveField(
            model_name='products_men',
            name='featured',
        ),
        migrations.RemoveField(
            model_name='products_men',
            name='image',
        ),
        migrations.RemoveField(
            model_name='products_men',
            name='price',
        ),
        migrations.RemoveField(
            model_name='products_women',
            name='active',
        ),
        migrations.RemoveField(
            model_name='products_women',
            name='category',
        ),
        migrations.RemoveField(
            model_name='products_women',
            name='description',
        ),
        migrations.RemoveField(
            model_name='products_women',
            name='discount_price',
        ),
        migrations.RemoveField(
            model_name='products_women',
            name='featured',
        ),
        migrations.RemoveField(
            model_name='products_women',
            name='image',
        ),
        migrations.RemoveField(
            model_name='products_women',
            name='price',
        ),
    ]
