# Generated by Django 2.2.13 on 2020-07-10 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0051_auto_20200710_1302'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Products_Men',
        ),
        migrations.DeleteModel(
            name='Products_Women',
        ),
    ]
