# Generated by Django 2.2.13 on 2020-07-10 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0052_auto_20200710_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='title',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
