# Generated by Django 2.2.13 on 2020-07-10 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0053_about_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='title',
        ),
    ]
