# Generated by Django 2.2.13 on 2020-07-10 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0054_remove_about_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About',
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
