# Generated by Django 2.2.13 on 2020-07-10 08:45

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0057_auto_20200710_1413'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aboutus', ckeditor_uploader.fields.RichTextUploadingField()),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contactus', ckeditor_uploader.fields.RichTextUploadingField()),
            ],
        ),
        migrations.DeleteModel(
            name='Aboutus',
        ),
        migrations.DeleteModel(
            name='Contactus',
        ),
    ]
