# Generated by Django 2.2.13 on 2020-07-10 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0062_contact_form_contact_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact_Form',
        ),
    ]
