# Generated by Django 2.2.13 on 2020-07-10 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0065_auto_20200710_1737'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Message',
            new_name='Message12',
        ),
    ]
