# Generated by Django 2.2.13 on 2020-07-10 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0066_auto_20200710_1738'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message12',
        ),
    ]
