# Generated by Django 2.2.13 on 2020-07-12 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0068_message1234'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message1234',
        ),
    ]
