# Generated by Django 2.2.13 on 2020-07-12 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0070_message1234'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Message1234',
            new_name='User_Message',
        ),
    ]
