# Generated by Django 2.2.13 on 2020-07-16 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0072_customer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
