# Generated by Django 2.2.13 on 2020-07-07 10:08

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200707_1508'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('obejcts', django.db.models.manager.Manager()),
            ],
        ),
    ]
