# Generated by Django 2.2.13 on 2020-07-07 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200707_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Full_Name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
