# Generated by Django 2.2.13 on 2020-07-17 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20200717_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='Image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
