# Generated by Django 2.2.13 on 2020-07-17 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20200717_2057'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
