# Generated by Django 2.2.13 on 2020-07-17 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_userprofile1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile1',
            name='image',
            field=models.ImageField(upload_to='images/users/'),
        ),
    ]
