# Generated by Django 2.2.13 on 2020-07-18 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20200717_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile1',
            name='image',
            field=models.ImageField(default='shop/static/images/awfy.png', upload_to='images/users/'),
        ),
    ]
