# Generated by Django 2.2.13 on 2020-07-18 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_remove_user_username'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserProfile',
            new_name='UserProfile1',
        ),
    ]
