# Generated by Django 2.2.13 on 2020-07-17 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0024_auto_20200716_2303'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='amount',
            new_name='Quantity',
        ),
    ]
